### ISSUE TITLE
Up to date?

### ISSUE THREAD

**Issue by Blucky87** [sschmid/Entitas-Standalone#2]
Will this generate code for my pure C# project that is compatible with 1.4.2 of Entitas?

**Comment by zhuchun** [comment]
Bump, asking similar question [here](https://github.com/sschmid/Entitas-CSharp/issues/706)

**Comment by MrMonotone** [comment]
I would like to know this information as well.

**Comment by zhuchun** [comment]
@MrMonotone Check my link above

**Comment by sschmid** [comment]
Now it is up to date again!

I recreated this project from scratch using Entitas 1.14 and force pushed.
See readme for code generation instructions.

It's now updated to .Net 6.0
